name       : homebank
version    : 5.1.7
release    : 10
source     :
    - http://homebank.free.fr/public/homebank-5.1.7.tar.gz : 579e53c00764b78d79e8e388b9202c760a9c9efdaca83b32d948f92e0dfa5fa7
license    : GPL-2.0
component  : office.finance
summary    : HomeBank assists you to manage your personal accounting.
description: |
    HomeBank is a free software (as in "free speech" and also as in "free beer") that will assist you to manage your personal accounting.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libofx)
    - pkgconfig(libsoup-2.4)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
