name       : homebank
version    : 5.1.1
release    : 3
source     :
    - http://homebank.free.fr/public/homebank-5.1.1.tar.gz : 9cd36ddc6931fd95ef5bcc6a723b3df0651b32e19465570d223c21ac1d5aa4bd
license    : GPL-2.0
component  : office
summary    : HomeBank assists you to manage your personal accounting.
description: |
    HomeBank is a free software (as in "free speech" and also as in "free beer") that will assist you to manage your personal accounting.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libofx)
    - pkgconfig(libsoup-2.4)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
