name       : homebank
version    : 5.1.6
release    : 8
source     :
    - http://homebank.free.fr/public/homebank-5.1.6.tar.gz : 2861e11590a00f5cbc505293821cb8caeabb74c26babe8a6a9d728f3404290e0
license    : GPL-2.0
component  : office.finance
summary    : HomeBank assists you to manage your personal accounting.
description: |
    HomeBank is a free software (as in "free speech" and also as in "free beer") that will assist you to manage your personal accounting.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libofx)
    - pkgconfig(libsoup-2.4)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
