name       : homebank
version    : 5.1.2
release    : 4
source     :
    - http://homebank.free.fr/public/homebank-5.1.2.tar.gz : d0dd12fcd41e2a23879a3f8378008436abb011d6cb7b0da9268f213d68c1fa27
license    : GPL-2.0
component  : office
summary    : HomeBank assists you to manage your personal accounting.
description: |
    HomeBank is a free software (as in "free speech" and also as in "free beer") that will assist you to manage your personal accounting.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libofx)
    - pkgconfig(libsoup-2.4)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
