name       : homebank
version    : 5.0.9
release    : 2
source     :
    - http://homebank.free.fr/public/homebank-5.0.9.tar.gz : d0bc763e94da0cba544495b07070e79faecf1d5de0cfb092d126482525e062b7
license    : GPL-2.0
component  : office
summary    : HomeBank assists you to manage your personal accounting.
description: |
    HomeBank is a free software (as in "free speech" and also as in "free beer") that will assist you to manage your personal accounting.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libofx)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
