name       : homebank
version    : 5.5.7
release    : 24
source     :
    - http://homebank.free.fr/public/homebank-5.5.7.tar.gz : ada0165f2883ca47af3cea8907c05e6080bc2d04274deebb58bd84b00c3b2838
homepage   : http://homebank.free.fr/en/index.php
license    : GPL-2.0-or-later
component  : office.finance
summary    : HomeBank assists you to manage your personal accounting
description: |
    HomeBank is a free software (as in "free speech" and also as in "free beer") that will assist you to manage your personal accounting.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libofx)
    - pkgconfig(libsoup-2.4)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
