name       : homebank
version    : 5.5.4
release    : 21
source     :
    - http://homebank.free.fr/public/homebank-5.5.4.tar.gz : 0d0669bca099340ae5c213ea13cb2b93283bfc8a0e4cf7a5902c1829366e5765
homepage   : http://homebank.free.fr/en/index.php
license    : GPL-2.0-or-later
component  : office.finance
summary    : HomeBank assists you to manage your personal accounting
description: |
    HomeBank is a free software (as in "free speech" and also as in "free beer") that will assist you to manage your personal accounting.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libofx)
    - pkgconfig(libsoup-2.4)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
