name       : homebank
version    : 5.1.3
release    : 5
source     :
    - http://homebank.free.fr/public/homebank-5.1.3.tar.gz : 22b2baf2e66fee2f97c7a6050298aa6d2502d75f02f046259e4181512714fb73
license    : GPL-2.0
component  : office
summary    : HomeBank assists you to manage your personal accounting.
description: |
    HomeBank is a free software (as in "free speech" and also as in "free beer") that will assist you to manage your personal accounting.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libofx)
    - pkgconfig(libsoup-2.4)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
